name: Deployment
on:
  push:
    branches:
      - master
    paths:
      - '**'
  release:
    branches:
      - master
    types: [created]
    paths:
      - '**'

jobs:
  deployment:
    name: Deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Create directory for owl files
        run: |
              mkdir -p $GITHUB_WORKSPACE/build/owl/current &&
              mkdir mkdir -p $GITHUB_WORKSPACE/build/files

      - name: Compile current
        if: startsWith(github.ref, 'refs/tags/') != true
        uses: docker://swipl:8.0.3
        with:
          SOMA_VERSION: current
          args: swipl -f prolog/uglify.pl -t uglify

      - name: Compile tag
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker://swipl:8.0.3
        with:
          SOMA_VERSION: ${{ github.event.release.tag_name }}
          args: swipl -f prolog/uglify.pl -t uglify

      - name: Convert
        uses: ./.github/actions/convert
        with:
          args: python3 ./scripts/uglify_ease_as_owl.py

      - name: Upload SOMA
        uses: actions/upload-artifact@v1
        with:
          name: SOMA Ontology
          path: ./build/owl/current/SOMA.owl

      - name: Upload SOMA-HOME
        uses: actions/upload-artifact@v1
        with:
          name: SOMA-HOME Ontology
          path: ./build/owl/current/SOMA-HOME.owl

      - name: Upload DUL
        uses: actions/upload-artifact@v1
        with:
          name: DUL Ontology
          path: ./owl/DUL.owl

      - name: Copy all OWL files to be deployed
        run: sudo cp -n ./owl/*.owl $GITHUB_WORKSPACE/build/owl/current

      - name: Metrics
        run: sudo ./scripts/OntoMetrics.sh $GITHUB_WORKSPACE/build/owl/current/SOMA.owl $GITHUB_WORKSPACE/build/files

      - name: Upload Metrics
        uses: actions/upload-artifact@v1
        with:
          name: Metrics
          path: ./build/files/metrics.json
      
      - name: Compile NEEM Handbook
        uses: docker://blang/latex:ubuntu
        with:
          args: make -f ./docs/NEEM-handbook/Makefile
      
      - name: Copy NEEM Handbook
        run: sudo cp $GITHUB_WORKSPACE/docs/NEEM-handbook/main.pdf $GITHUB_WORKSPACE/build/files/NEEM-Handbook.pdf
      
      - name: Deploy files
        uses: JamesIves/github-pages-deploy-action@releases/v3
        if: github.ref == 'refs/heads/master'
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build/files
          TARGET_FOLDER: /files

      - name: Deploy current
        uses: JamesIves/github-pages-deploy-action@releases/v3
        if: github.ref == 'refs/heads/master'
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build/owl/current/
          TARGET_FOLDER: /owl/current

      - name: Deploy tag
        uses: JamesIves/github-pages-deploy-action@releases/v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build/owl/current/
          TARGET_FOLDER: owl/${{ github.event.release.tag_name }}
          #TARGET_FOLDER: owl/${{ GITHUB_REF/refs\/tags\// }}
          #TARGET_FOLDER: owl/${{ GITHUB_REF#refs/tags/ }}

      - name: Deploy failure
        if: failure()
        run: echo Deployment failed. If the other steps succeeded, maybe no ACCESS_TOKEN was set?
