name: Documentation
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Evaluation"]
    types:
      - completed

jobs:
  vocabulary:
    name: SOMA Vocabulary
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docs/vocab/

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download OWL file
        uses: actions/download-artifact@v2
        with:
          name: SOMA-OWL
          path: ./build/owl/current/

      - name: Copy
        run: |
          cp ./Makefile ../../
          cp ./SOMA-vocabulary.tex ../../
          cp ./owl_reader.py ../../

      - name: Build
        uses: ./.github/actions/pythonlatex
        with:
          args: make

      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          name: SOMA Vocabulary
          path: ./SOMA-vocabulary.pdf

  handbook:
    name: NEEM Handbook
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Build
        uses: docker://blang/latex:ubuntu
        with:
          args: make -f ./docs/NEEM-handbook/Makefile

      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          name: NEEM Handbook
          path: ./docs/NEEM-handbook/main.pdf
