name: Documentation
on:
  push:
    paths:
      - 'docs/**'

jobs:
  documentation:
    name: Documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Cache Template
        id: cache-template
        uses: actions/cache@v1
        with:
          path: ./template
          key: https://resource-cms.springernature.com/springer-cms/rest/v1/content/20568/data/v8

      - name: Download Template
        if: steps.cache-template.outputs.cache-hit != 'true'
        run: curl -o ./template.zip -L https://resource-cms.springernature.com/springer-cms/rest/v1/content/20568/data/v8

      - name: Unzip Template
        if: steps.cache-template.outputs.cache-hit != 'true'
        run: unzip -d ./template template.zip

      - name: Build
        uses: docker://blang/latex:ubuntu
        env:
          TEXINPUTS: "/github/workspace/template:"
        with:
          args: make -f ./docs/NEEM-specification/Makefile

      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          name: NEEM Handbook
          path: ./docs/NEEM-specification/main.pdf
